#!/bin/bash

[[ -e /etc/newadm-instalacao ]] && BASICINST="$(cat /etc/newadm-instalacao)" || 
BASICINST="ADMbot.sh apacheon.sh blockBT.sh budp.sh Crear-Demo.sh C-SSR.sh dns-netflix.sh dropbear.sh fai2ban.sh gestor.sh menu message.txt openvpn.sh paysnd.sh PDirect.py PGet.py POpen.py ports.sh PPriv.py PPub.py shadowsocks.sh Shadowsocks-libev.sh Shadowsocks-R.sh sockspy.sh speed.sh speedtest.py squid.sh squidpass.sh ssl.sh tcp.sh ultrahost Unlock-Pass-VULTR.sh usercodes utils.sh v2ray.sh"
SCPT_DIR="/etc/SCRIPT"
IVAR="/etc/http-instas"
usadas="/etc/http-instas"
[[ ! -e ${SCPT_DIR} ]] && mkdir ${SCPT_DIR}
INSTA_ARQUIVOS="ADMVPS.zip"
DIR="/etc/http-shell"
LIST="MDAKTSOHG"

gerar_key () {
meu_ip_fun
limcont=$(cat /etc/ADM-db/limit) 
[[ "$limcont" -ge "998" ]] && limted=" ∞ " || limted=$(cat /etc/ADM-db/limit)
valuekey="$(date | md5sum | head -c10)"
valuekey+="$(echo $(($RANDOM*10))|head -c 5)"
#oUP=$(wget -qO- ipv4.icanhazip.com)
fun_list "$valuekey"
#keyfinal="$(ofus "$oUP:8888/${valuekey}/$LIST")"
keyfinal=$(ofus "$IP:8888/$valuekey/$LIST")
local bot_retorno="$LINE\n"
bot_retorno+="  🔰 Key Generada Exitosamente! 🔰\n ⚠️ Autodestruccion 24 horas o al Usarla ⚠️\n"
bot_retorno+="$LINE\n"
bot_retorno+="  ⚠️ B O T G E N By G H O S T ⚠️\n"
bot_retorno+="$LINE\n"
bot_retorno+=" 🛡️ Reseller 🛡️ : [$message_from_first_name $message_from_last_name] \n"
bot_retorno+="$LINE\n"
bot_retorno+="        💥 KEY FINAL GENERADA 💥\n"
bot_retorno+="$LINE\n"
bot_retorno+="<code>${keyfinal}</code>\n"
bot_retorno+="$LINE\n"
bot_retorno+="  🛡️  ENLACE DE INSTALADOR OFICIAL  🛡️\n"
bot_retorno+="$LINE\n"
bot_retorno+="<code>apt update-y; apt upgrade -y; wget https://www.dropbox.com/s/sbo9bri6nissapa/instalscript.sh; chmod 777 instalscript.sh; ./instalscript.sh</code>\n"
bot_retorno+="$LINE\n"
bot_retorno+="🚀 Soporte : Ubuntu 18.04 - 20.04\n    💻 SO Recomendado: Ubuntu 18.04 \n 💳 Solicita tu Acceso 💳\n"
bot_retorno+="$LINE\n"
bot_retorno+=" 🔐 『 $(cat /etc/http-instas) 』keys Usadas 🔓『 $numkey_gen 』keys Generadas \n"
bot_retorno+="$LINE\n"
msj_fun
echo -e $bot_retorno >> ${keytxt}/key_${chatuser}.txt
upfile_fun ${keytxt}/key_${chatuser}.txt
rm ${keytxt}/key_${chatuser}.txt
}

fun_list () {
rm ${SCPT_DIR}/*.x.c &> /dev/null
unset KEY
KEY="$1"
echo $KEY >> /root/ID-tses
#CRIA DIR
[[ ! -e ${DIR} ]] && mkdir ${DIR}
#ENVIA ARQS
i=0
VALUE+="gerar.sh instgerador.sh http-server.py lista-arq $BASICINST"
for arqx in `ls ${SCPT_DIR}`; do
[[ $(echo $VALUE|grep -w "${arqx}") ]] && continue
echo -e "[$i] -> ${arqx}"
arq_list[$i]="${arqx}"
let i++
done
#CRIA KEY
[[ ! -e ${DIR}/${KEY} ]] && mkdir ${DIR}/${KEY}
#PASSA ARQS
[[ ! $usadas ]] && k_used="0" 
nombrevalue="${chatuser}"
echo "$nombrevalue" >> /etc/ADM-db/num-key.cont
#numkey_used=$(grep -o -i $nombrevalue /etc/gerar-sh-log | wc -l)
numkey_gen=$(grep -o -i $nombrevalue /etc/ADM-db/num-key.cont | wc -l)
#ADM BASIC
arqslist="$BASICINST"
for arqx in `echo "${arqslist}"`; do
[[ -e ${DIR}/${KEY}/$arqx ]] && continue #ANULA ARQUIVO CASO EXISTA
cp ${SCPT_DIR}/$arqx ${DIR}/${KEY}/
echo "$arqx" >> ${DIR}/${KEY}/${LIST}
done
rm ${SCPT_DIR}/*.x.c &> /dev/null
echo "$nombrevalue" > ${DIR}/${KEY}.name
[[ ! -z $IPFIX ]] && echo "$IPFIX" > ${DIR}/${KEY}/keyfixa
at now +30 minutes <<< "rm -rf ${DIR}/${KEY} && rm -rf ${DIR}/${KEY}.name"
}

ofus () {
unset server
server=$(echo ${txt_ofuscatw}|cut -d':' -f1)
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="*";;
"*")txt[$i]=".";;
"1")txt[$i]="@";;
"@")txt[$i]="1";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"4")txt[$i]="%";;
"%")txt[$i]="4";;
"-")txt[$i]="K";;
"K")txt[$i]="-";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}

