#!/bin/bash
[[ -e /etc/ADM-db/idioma_menuinst ]] && tr=$(cat < /etc/ADM-db/idioma_menuinst)
text1=$(source trans -b pt:${tr} "MENU DE COMANDOS ")
text2=$(source trans -b pt:${tr} "INSTRUCCIONES DE COMANDOS ")

menu_src () {
bot_retorno="$LINE\n"
bot_retorno+=" ✦҈͜͡➳             ⚜️PANEL⚜️ \n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
		 	 bot_retorno+="$LINE\n"
			 bot_retorno+="👋Hola ($message_from_first_name $message_from_last_name), Bienvenido al Menu.\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="  ⚠️ TENDRAS ACCESO LIMITADO ⚠️ \n  🚫 Sin TU RESELLER EN LA KEY 🚫\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Bienvenido [ @$message_from_username ], $(source trans -b pt:${tr} "tu ID No Fue autorizado, Realiza una Donacion ") \n"
			 bot_retorno+="$LINE\n"
                         bot_retorno+="/ID    | Muestra tu ID. \n"
			 bot_retorno+="/menu  | MENU DE COMANDOS.\n"
			 bot_retorno+="/ayuda | INSTRUCCIONES DE COMANDOS.\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Si tienes inconvenientes con el BotGEN \n Contactame : \n $(cat < /etc/ADM-db/resell)\n"
			 bot_retorno+="$LINE\n"
			 msj_fun
		 else
		 	[[ -e /etc/menu_ito ]] && nomkey="$(cat /etc/menu_ito)" || nomkey="$(curl -sSL "https://raw.githubusercontent.com/ADM-PERU/MGRBOT/main/TeleBotGen/Control/menu_credit")"
		 	numkey_used=$(grep -o -i $message_chat_id /etc/gerar-sh-log | wc -l)
			numkey_gen=$(grep -o -i $message_chat_id /etc/ADM-db/num-key.cont | wc -l)
			bot_retorno+="$LINE\n"
			 bot_retorno+="  ⚠️ TENDRAS ACCESO ILIMITADO ⚠️ \n  ✓ INCLUIDO TU RESELLER EN LA KEY ✓ \n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="👋Hola [$message_from_first_name $message_from_last_name], Bienvenido al Menu\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+=" Reseller Actual ☞ $message_from_first_name $message_from_last_name\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="/ID        |   MUESTRA TU ID PERSONAL.\n"
			 bot_retorno+="/instal    |   LINK DE SCRIPT.\n"
			 bot_retorno+="/menu      |   MENU DE ACCIONES PERMITIDAD.\n"
			 bot_retorno+="/ayuda     |   INSTRUCCIONES DEL BOT.\n"
			 bot_retorno+=" ❊ 𝚁𝚎𝚌𝚞𝚎𝚛𝚍𝚊 𝙲𝚘𝚕𝚊𝚋𝚘𝚛𝚊𝚛 💸💰 , 𝚜𝚒 𝚝𝚎 𝚊𝚐𝚛𝚊𝚍𝚘 𝚖𝚒 𝚃𝚛𝚊𝚋𝚊𝚓𝚘 ❊\n"
			 bot_retorno+="Si tienes inconvenientes con el Bot  🎁 Contactame : +$(cat < /etc/numctc) 📲\n"
			 bot_retorno+=" 🔐 『 $numkey_used 』Key usadas ➖ ,『 $numkey_gen 』Key generada 🔑 \n"
			 bot_retorno+="$LINE\n"
			 menu_print
		 fi
		 
	 else
		 unset PID_GEN
		 
		 PID_GEN=$(ps x|grep -v grep|grep "8888")
		 [[ ! $PID_GEN ]] && PID_GEN='(💔) OFF' || PID_GEN='(💚) ON'
		 unset usadas
		 usadas="$(cat /etc/http-instas)"
		 [[ ! $usadas ]] && k_used="0" || k_used="$usadas"
		 bot_retorno+="Gen $PID_GEN | Keys Used [$k_used]\n"
		 bot_retorno+="⚕️OWNER : @$message_from_username ➖ $(printf '%(%D)T')\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="/infosys   ➩ 	INFORMACION DEL VPS \n"
		 bot_retorno+="/list	 ➩ 	MUESTRA LISTA DE ID PERMITIDOS\n"
		 bot_retorno+="/instal	 ➩ 	INSTALADOR OFICIAL \n"
		 bot_retorno+="/menu	 ➩ 	MENU DE ACCIONES \n"
		 bot_retorno+="/ayuda	 ➩	INSTRUCCIONES DE COMANDOS \n"
		 bot_retorno+="/cache	 ➩	OPTIMIZA SERVIDOR \n"
		 bot_retorno+="/update 	 ➩	ACTUALIZA BOT \n"
		 bot_retorno+="/reboot	 ➩	REINICIA SERVIDOR VPS \n"
                 bot_retorno+="/donar 	 ➩	ACTIVA OPCION PARA DONAR \n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="Gen $PID_GEN | Keys Used [$k_used]\n"
                 bot_retorno+="$LINE\n"
		 menu_print
	 fi	
}
