#!/bin/bash
[[ -e /etc/ADM-db/idioma_menuinst ]] && tr=$(cat < /etc/ADM-db/idioma_menuinst)
text1=$(source trans -b pt:${tr} "MENU DE COMANDOS ")
text2=$(source trans -b pt:${tr} "INSTRUCCIONES DE COMANDOS ")

menu_src () {
bot_retorno="$LINE\n"
bot_retorno+="✦҈‌➳                  ⚜️PANEL⚜️\n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
		 	 bot_retorno+="$LINE\n"
			 bot_retorno+="👋Hola ($message_from_first_name $message_from_last_name), Bienvenido al menu\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="  ⚠️ TENDRAS ACCESO LIMITADO ⚠️ \n  🚫 Sin TU RESELLER EN LA KEY 🚫\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Bienvenido  @$message_from_username , $(source trans -b pt:${tr} , tu ID no fue autorizado, realiza una donación.\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="/ID    | Muestra su ID.\n"
			 bot_retorno+="/menu  | $text1 \n"
			 bot_retorno+="/ayuda | $text2 \n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Si tienes inconvenientes con el BotGEN \n contactame : @GHOST\n"
			 bot_retorno+="$LINE\n"
			 msj_fun
		 else
		 	[[ -e /etc/menu_ito ]] && nomkey="$(cat /etc/menu_ito)" || nomkey="$(curl -sSL "https://raw.githubusercontent.com/ADM-PERU/MGRBOT/main/TeleBotGen/Control/menu_credit")"
		 	numkey_used=$(grep -o -i $message_chat_id /etc/gerar-sh-log | wc -l)
			numkey_gen=$(grep -o -i $message_chat_id /etc/ADM-db/num-key.cont | wc -l)
			bot_retorno+="$LINE\n"
			 bot_retorno+="  ⚠️ TENDRAS ACCESO ILIMITADO ⚠️ \n  🚫 Sin TU RESELLER EN LA KEY 🚫\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="👋Hola $message_from_first_name $message_from_last_name, bienvenido al menu\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Reseller Actual: $nomkey\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="/ID     ✨  Muestra su ID.\n"
			 bot_retorno+="/instal ✨  Link de instalador oficial.\n"
			 bot_retorno+="/menu   ✨  Menu de comandos disponibles.\n"
			 bot_retorno+="/ayuda  ✨  Instrucciónes delmenú.\n"
			 bot_retorno+="Si tienes inconvenientes con el Bot, Contactame  : @GHOST 📲\n"
			 bot_retorno+=" 🔐  $numkey_used Keys usadas ➖ $numkey_gen  Keys generadas 🔑\n"
			 bot_retorno+="$LINE\n"
			 menu_print
		 fi
		 
	 else
		 unset PID_GEN
		 
		 PID_GEN=$(ps x|grep -v grep|grep "http-server.sh")
		 [[ ! $PID_GEN ]] && PID_GEN='(Offline) ❌' || PID_GEN='(Online) ✅'

		 unset usadas
		 usadas="$(cat /etc/http-instas)"
		 [[ ! $usadas ]] && k_used="0" || k_used="$usadas"
		 bot_retorno+="⚜️OWNER: @$message_from_username | $(printf '%(%D)T')\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="/infosys 🔹️ INFORMACION DEL SERVIDOR\n"
		 bot_retorno+="/list   🔹️ MUESTRA LISTA DE ID PERMITIDOS\n"
		 bot_retorno+="/instal 🔹️ INSTALADOR OFICIAL\n"
		 bot_retorno+="/menu 🔹️ MENU DE ACCIONES\n"
		 bot_retorno+="/ayuda 🔹️ INSTRUCCIONES DE COMANDOS\n"
		 bot_retorno+="/cache 🔹️ OPTIMIZA SERVIDOR\n"
		 bot_retorno+="/update 🔹️ ACTUALIZA BOT\n"
		 bot_retorno+="/reboot 🔹️ REINICIA SERVIDOR VPS\n"
		 bot_retorno+="/donar 🔹️ ACTIVA OPCION PARA DONAR\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="Gen $PID_GEN | Keys Used [$k_used]\n"
                 bot_retorno+="$LINE\n"
		 menu_print
	 fi	
}
